---
title           : "Psychological Needs During Intergroup Contact: An Extensive Longitudinal Study (Young Medical Professionals Sample)"
shorttitle      : "Preregistration: Needs During Intergroup Contact"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"
author: 
  - name        : Jannis Kreienkamp
    affiliation : "1"
  - name        : Maximilian Agostini
    affiliation : "1"
  - name        : Laura Bringmann
    affiliation : "1"
  - name        : Peter de Jonge
    affiliation : "1"
  - name        : Kai Epstude
    affiliation : "1"
affiliation:
  - id          : 1
    institution : University of Groningen, Department of Psychology
bibliography: "../references.bib"
csl: apa.csl
biblio-style: "apalike" 
output: 
  prereg::cos_prereg:
    citation_package: natbib
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
# R Studio Clean-Up
  cat("\014") # clear console
  #rm(list=ls()) # clear workspace - use restart R instead [cmd/alt + shift + F10]
  gc() # garbage collector
  
# Install and Load Packages
# !IMPORTANT!
# BEFORE FIRST RENDER:
# To install all relevant packages please run "renv::restore()" (or renv::init() and then initiate from lockfile) in the console before the first use to ensure that all packages are using the correct version.
# to store the packages in a contained library within the project folder: renv::settings$use.cache(FALSE) and add 'RENV_CONFIG_SANDBOX_ENABLED = FALSE' to an '.Renviron' file 
lib <- c("rmarkdown", "knitr", "remedy", "bookdown", "psych",
         "ggplot2", "ggthemes", "haven", "RColorBrewer", "plotly", "gridExtra",
         "sessioninfo", "tibble", "pander", "devtools",
         "data.table", "dplyr", "tidyr", "Hmisc", "kableExtra", 
         "stringr", "stringi", "reshape2", "lubridate")
invisible(lapply(lib, library, character.only = TRUE))  
rm(lib)  

# Markdown Options
  knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file()) # set working directory

# Global Chunk Options
  knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figures/',
                        echo=TRUE, warning=FALSE, message=FALSE)
```

# Study Information

## Title
<!-- Provide the working title of your study. It may be the same title that you submit for publication of your final manuscript, but it is not a requirement. The title should be a specific and informative description of a project. Vague titles such as 'Fruit fly preregistration plan' are not appropriate.

Example: Effect of sugar on brownie tastiness. -->

`r rmarkdown::metadata$title`


## Description
<!-- Please give a brief description of your study, including some background, the purpose of the of the study, or broad research questions. The description should be no longer than the length of an abstract. It can give some context for the proposed study, but great detail is not needed here for your preregistration.

Example: Though there is strong evidence to suggest that sugar affects taste preferences, the effect has never been demonstrated in brownies. Therefore, we will measure taste preference for four different levels of sugar concentration in a standard brownie recipe to determine if the effect exists in this pastry. -->

In its most essential interpretation, the intergroup contact hypothesis postulates that frequent and positive contact with an out-group reduces prejudice and increases favorable attitudes towards the other group [@Hewstone1996; @Pettigrew1998]. A key condition for these contact benefits has been that the interaction is perceived as positive --- making the interaction quality a crucial mechanism of inter-group contact [e.g., @MacInnis2015]. It is widely accepted that equal status, common goals, collaboration, and structural support during the interaction form the optimal conditions for a positive contact [Allport's Optimal Contact conditions, @Allport1954b]. And indeed a major meta-analytic review showed, that intergroup contact benefits were larger when Allport's conditions were met. However, the meta-analysis also showed that contact resulted in more positive intergroup relations even when Allport's conditions were not met [@Pettigrew2006]. It, thus, remains unclear why and how exactly Allport's conditions work.

We propose that Allport's optimal contact conditions are effective in creating positive contact because they constitute common psychological needs of the interacting individuals. If this is indeed the case, the impact of fulfilling other fundamental needs should produce similar beneficial contact results. And more importantly, the satisfaction of key situation needs during the interaction should predict the positive contact effects most strongly.


## Hypotheses
<!-- List specific, concise, and testable hypotheses. Please state if the hypotheses are directional or non-directional. If directional, state the direction. A predicted effect is also appropriate here. If a specific interaction or moderation is important to your research, you can list that as a separate hypothesis.

Example: If taste affects preference, then mean preference indices will be higher with higher concentrations of sugar. -->

1. \label{hyp:contact}Based on the most general understanding of the contact hypothesis, an increase in frequency and quality of contact should jointly account for changes in more favorable outgroup attitudes.
    a. \label{hyp:contactFreq}Participants with more intergroup interactions should have a more favorable outgroup attitudes.
    b. \label{hyp:contactDummy}Outgroup attitudes should be higher after an intergroup interaction compared to a non-outgroup interaction.
    c. \label{hyp:contactFreqQual}Participants with more intergroup interactions should have a more favorable outgroup attitudes depending on the average interaction quality.
2. \label{hyp:AllportsConditions}Based on Allport's optimal contact conditions, intergroup interactions with equal status, common goals, collaboration, and structural support should predict more favorable outgroup attitudes due to more positive interaction quality perceptions.
    a. \label{hyp:AllportsPred}Based on Allport's optimal contact conditions, outgroup attitudes should be more favorable after intergroup interactions with equal status, common goals, collaboration, and structural support.
    b. \label{hyp:AllportsQuality}Based on past research on the role of interaction quality, interaction quality should be more perceived as more favorable after intergroup interactions with equal status, common goals, collaboration, and structural support.
    c. \label{hyp:AllportsQualityMediation}Based on past research on the role of interaction quality, the variance explained in outgroup attitudes by Allport's optimal contact should to a large extend be assumed by interaction quality.
3. \label{hyp:keyNeed}Based on our proposal, intergroup interactions with higher situational core need fulfillment should predict more favorable outgroup attitudes due to more positive interaction quality perceptions.
    a. \label{hyp:keyNeedPred}Outgroup attitudes should be more favorable after intergroup interactions with high key need fulfillment.
    b. \label{hyp:keyNeedQual}Interaction Quality should be perceived as more positive after intergroup interactions with higher key need fulfillment.
    c. \label{hyp:keyNeedMediation}The variance explained in outgroup attitudes by key need fulfillment should to a large extend be assumed by interaction quality.
    d. \label{hyp:keyNeedContactType}The effect of key need fulfillment on outgroup attitudes should be specific to intergroup interactions and not be due to need fulfillment in general. Thus, the effect of key need fulfillment on outgroup attitudes should stronger for intergroup interact than for ingroup interactions.
    e. \label{hyp:keyNeedSDT}The effect of key need fulfillment on outgroup attitudes should be persist even when taking other fundamental psychological needs into account. Thus, the effect of key need fulfillment on outgroup attitudes should remain strong even after controlling for autonomy, competence, and relatedness fulfillment during the interaction (cf., self-determination theory). 
4. \label{hyp:comparison}Based on our proposal, intergroup interactions with higher situational core need fulfillment should predict outgroup attitudes at least as well as Allport's conditions.
    a. \label{hyp:compModel}The need model (H\ref{hyp:keyNeedPred}) should predict more variance in outgroup attitudes than the model based on Allport's conditions (H\ref{hyp:AllportsPred}).
    b. \label{hyp:compTogether}The  effect of key need fulfillment on outgroup attitudes should  persist even when taking other Allport's conditions into account. Thus, the effect of key need fulfillment on outgroup attitudes should remain strong even after controlling for equal status, common goals, collaboration, and structural support.

# Design Plan
<!-- In this section, you will be asked to describe the overall design of your study. Remember that this research plan is designed to register a single study, so if you have multiple experimental designs, please complete a separate preregistration. -->


## Study type

**Observational Study**. Data is collected from study subjects that are not randomly assigned to a treatment. This includes surveys, natural experiments, and regression discontinuity designs.


## Blinding
<!-- Blinding describes who is aware of the experimental manipulations within a study. Select all that apply. Is there any additional blinding in this study? -->

No participant blinding is involved in this study.

## Study design
<!-- Describe your study design. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required. Typical study designs for observation studies include cohort, cross sectional, and case-control studies.

This question has a variety of possible answers. The key is for a researcher to be as detailed as is necessary given the specifics of their design. Be careful to determine if every parameter has been specified in the description of the study design. There may be some overlap between this question and the following questions. That is OK, as long as sufficient detail is given in one of the areas to provide all of the requested information. For example, if the study design describes a complete factorial, 2 X 3 design and the treatments and levels are specified previously, you do not have to repeat that information.

Example: We have a between subjects design with 1 factor (sugar by mass) with 4 levels. -->

This study used an extensive longitudinal design. Using a daily diary format, for at least 30 days participants received a short survey twice per day (at around 12pm and 7pm). We additionally included a longer pre- and post measurement survey the days before and after the extensive longitudinal data collection.


## Randomization
<!-- If you are doing a randomized study, how will you randomize, and at what level? Typical randomization techniques include: simple, block, stratified, and adaptive covariate randomization. If randomization is required for the study, the method should be specified here, not simply the source of random numbers.

Example: We will use block randomization, where each participant will be randomly assigned to one of the four equally sized, predetermined blocks. The random number list used to create these four blocks will be created using the web applications available at https://random.org. -->

No randomization is involved in this study.


# Sampling Plan
<!-- In this section we’ll ask you to describe how you plan to collect samples, as well as the number of samples you plan to collect and your rationale for this decision. Please keep in mind that the data described in this section should be the actual data used for analysis, so if you are using a subset of a larger dataset, please describe the subset that will actually be used in your study. -->


## Existing data
<!-- Preregistration is designed to make clear the distinction between confirmatory tests, specified prior to seeing the data, and exploratory analyses conducted after observing the data. Therefore, creating a research plan in which existing data will be used presents unique challenges. Please select the description that best describes your situation. Please do not hesitate to contact us if you have questions about how to answer this question (prereg@cos.io). -->

**Registration prior to accessing the data**. As of the date of submission, the data exist, but have not been accessed by you or your collaborators. Commonly, this includes data that has been collected by another researcher or institution.

## Explanation of existing data
<!-- If you indicate that you will be using some data that already exist in this study, please describe the steps you have taken to assure that you are unaware of any patterns or summary statistics in the data. This may include an explanation of how access to the data has been limited, who has observed the data, or how you have avoided observing any analysis of the specific data you will use in your study.

An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point.

Example: An appropriate instance of using existing data would be collecting a sample size much larger than is required for the study, using a small portion of it to conduct exploratory analysis, and then registering one particular analysis that showed promising results. After registration, conduct the specified analysis on that part of the dataset that had not been investigated by the researcher up to that point. -->

The data was collected as part of a larger collaboration on daily intergroup relations. The researchers have had no direct access to the data, as the data was collected using an automated system using the FormR framework [@Arslan2020]. The data were then downloaded and stored securely on an encrypted device until the eventual data analysis. None of the researchers have accessed the data thus far.


## Data collection procedures
<!-- Please describe the process by which you will collect your data. If you are using human subjects, this should include the population from which you obtain subjects, recruitment efforts, payment for participation, how subjects will be selected for eligibility from the initial pool (e.g. inclusion and exclusion rules), and your study timeline. For studies that donÍt include human subjects, include information about how you will collect samples, duration of data gathering efforts, source or location of samples, or batch numbers you will use.

The answer to this question requires a specific set of instructions so that another person could repeat the data collection procedures and recreate the study population. Alternatively, if the study population would be unable to be reproduced because it relies on a specific set of circumstances unlikely to be recreated (e.g., a community of people from a specific time and location), the criteria and methods for creating the group and the rationale for this unique set of subjects should be clear.

Example: Participants will be recruited through advertisements at local pastry shops. Participants will be paid $10 for agreeing to participate (raised to $30 if our sample size is not reached within 15 days of beginning recruitment). Participants must be at least 18 years old and be able to eat the ingredients of the pastries. -->

The data was collected in a three step procedure:

1. Entry Survey: A pre-measurement questionnaire (appr. 25 minutes) including demographic information, and relations to the Dutch majority. (payment: 2 Euros)
2. Experience Recaps: At least 30 days of short reflection surveys (appr. 3—5 minutes) on intergroup interactions twice a day. (payment: 1 Euro per Recap; up to 2 Euros per day)
3. Conclusion Survey: On the last day, we conclude with a post-measurement questionnaire (appr. 25 minutes) with some questions on habits and reflections on the study. (payment: 2 Euros)

After the initial 30 day duration, participants are offered the possibility to continue participating in the study either with payment if daily diary measures were missed during the initial study phase or without payment after a total of 60 daily diary measurements were completed. After the initial 30-day period, participants receive automated feedback visualizing the development of their own well-being, attitudes, and motive responses as an additional initiative to give participants access to their own data and to compensate study participation.

## Sample size
<!-- Describe the sample size of your study. How many units will be analyzed in the study? This could be the number of people, birds, classrooms, plots, interactions, or countries included. If the units are not individuals, then describe the size requirements for each unit. If you are using a clustered or multilevel design, how many units are you collecting at each level of the analysis? For some studies, this will simply be the number of samples or the number of clusters. For others, this could be an expected range, minimum, or maximum number.

Example: Our target sample size is 280 participants. We will attempt to recruit up to 320, assuming that not all will complete the total task. -->

Our target sample size is a sum of 4,000 daily diary measurements. With 100% completion rate that would be archived with 67 participants (60 daily diary responses each). Given that we expect some incomplete daily diary measurements, we aimed to recruit 80 participants.

## Sample size rationale
<!-- This could include a power analysis or an arbitrary constraint such as time, money, or personnel. This gives you an opportunity to specifically state how the sample size will be determined. A wide range of possible answers is acceptable; remember that transparency is more important than principled justifications. If you state any reason for a sample size upfront, it is better than stating no reason and leaving the reader to "fill in the blanks." Acceptable rationales include: a power analysis, an arbitrary number of subjects, or a number based on time or monetary constraints.

Example: We used the software program G*Power to conduct a power analysis. Our goal was to obtain .95 power to detect a medium effect size of .25 at the standard .05 alpha error probability. -->

The targeted sample size depended on a combination of different factors. Different analyses were planned as part of the collaboration and budgeting was a practical constraint. Some analyses were planned based on (1) the pre- to post measurements, (2) the dynamic developments over the daily diary measurements, or (3) the contemporary effects within the daily diary measurements.

Power considerations of mixed effects model such as with extensive longitudinal data are difficult to estimate because of the complex covariance structures. Simulation studies based on the first two samples within this project indicated that with well-distributed scales, and small to medium effect sizes, 70-80 participants with at least seven daily diary measurements and a simple pre--post survey were sufficiently powerful (power = .8, alpha = .05) to answer most of the key research questions of the collaboration.

The ultimate sampling procedure decision was made as a practical balancing of the number of participants and the number of measurements provided by each participants. Given that this study primarily focuses on the contemporaneous effects within the daily diary measurements, power should thus be high enough. 

## Stopping rule
<!-- If your data collection procedures do not give you full control over your exact sample size, specify how you will decide when to terminate your data collection. 

You may specify a stopping rule based on p-values only in the specific case of sequential analyses with pre-specified checkpoints, alphas levels, and stopping rules. Unacceptable rationales include stopping based on p-values if checkpoints and stopping rules are not specified. If you have control over your sample size, then including a stopping rule is not necessary, though it must be clear in this question or a previous question how an exact sample size is attained.

Example: We will post participant sign-up slots by week on the preceding Friday night, with 20 spots posted per week. We will post 20 new slots each week if, on that Friday night, we are below 320 participants. -->

Participants will be recruited until 80 participants finish the pre-measurement. Invitations to complete additional daily diary measurements will be extended until participants chose to leave the study or at the most until two months (i.e., 64 days) after the initial entry survey (i.e., from the pre measurement survey).

# Variables
<!-- In this section you can describe all variables (both manipulated and measured variables) that will later be used in your confirmatory analysis plan. In your analysis plan, you will have the opportunity to describe how each variable will be used. If you have variables which you are measuring for exploratory analyses, you are not required to list them, though you are permitted to do so. -->


## Manipulated variables
<!-- Describe all variables you plan to manipulate and the levels or treatment arms of each variable. This is not applicable to any observational study. For any experimental manipulation, you should give a precise definition of each manipulated variable. This must include a precise description of the levels at which each variable will be set, or a specific definition for each categorical treatment. For example, “loud or quiet,” should instead give either a precise decibel level or a means of recreating each level. 'Presence/absence' or 'positive/negative' is an acceptable description if the variable is precisely described.

Example: We manipulated the percentage of sugar by mass added to brownies. The four levels of this categorical variable are: 15%, 20%, 25%, or 40% cane sugar by mass. -->

Not applicable given that the study design is observational.


## Measured variables
<!-- Describe each variable that you will measure. This will include outcome measures, as well as any predictors or covariates that you will measure. You do not need to include any variables that you plan on collecting if they are not going to be included in the confirmatory analyses of this study.

Observational studies and meta-analyses will include only measured variables. As with the previous questions, the answers here must be precise. For example, 'intelligence,' 'accuracy,' 'aggression,' and 'color' are too vague. Acceptable alternatives could be 'IQ as measured by Wechsler Adult Intelligence Scale' 'percent correct,' 'number of threat displays,' and 'percent reflectance at 400 nm.'

Example: The single outcome variable will be the perceived tastiness of the single brownie each participant will eat. We will measure this by asking participants ‘How much did you enjoy eating the brownie’ (on a scale of 1-7, 1 being 'not at all', 7 being 'a great deal') and 'How good did the brownie taste' (on a scale of 1-7, 1 being 'very bad', 7 being 'very good'). -->

**Key variables:**

1. Whether an interaction happened during the past daytime period
    a. Did you meet a Dutch person this [morning/afternoon]?
    a. Did you meet a Non-Dutch person [morning/afternoon]?
1. Number of interactions during the past daytime period
    a. How many interactions with Dutch people did you have this [morning/afternoon]?
    a. How many interactions with Non-Dutch people did you have this [morning/afternoon]?
1. Key need assessment
    a. What was your main goal during the interaction with [name interaction partner]?
    a. During the interaction with [name interaction partner] your goal [free-text entry interaction key need] was fulfilled.
1. Allport's Conditions (equal status, common goal, collaboration, and structural support)
    a. The interaction with [name interaction partner] was on equal footing (same status)
    a. [name interaction partner] shared your goal ([free-text entry interaction key need])
    a. The interaction with [name interaction partner] was cooperative
    a. The interaction with [name interaction partner] was voluntary
1. Interaction Quality
    a. Overall, the interaction with [name interaction partner] was: Unpleasant to Pleasant
1. Outgroup Attitudes
    a. After the interaction, how favorably do you feel towards the Dutch.


**Control variables:**

1. Self Determination Theory needs ("During the interaction with [name interaction partner]")
    a. I was myself.
    a. I felt competent.
    a. I shared information about myself. 
    a. [name interaction partner] shared information about themselves.
1. General key need during daytime
    a. What was your main goal during this [morning/afternoon]?
    a. During this [morning/afternoon] your goal ([free-text entry daytime key need]) was fulfilled
    a. How important was your goal ([free-text entry daytime key need]) to you:
1. Student Goals ("Please rate the importance of each goal during the interaction with [name interaction partner]"):
    a. Social support / social connection goals
    a. Romantic or sexual relationship goals
    a. Academic goals
    a. Career goals
    a. Financial goals
    a. Health / fitness goals
    a. Leisure / fun goals
    a. Personal improvement / growth goals
    a. Service / helping goals
    a. Spiritual / religious goals


**Additional Analyses:**

1. Generalization from interaction partner to outgroup
    a. After the interaction, how favorably do you feel towards [name interaction partner].
    a. The interaction with [name interaction partner] was representative of the Dutch.
1. Alternative interaction quality definition ("Overall, the interaction with [name interaction partner] was ...")
    a. Unpleasant to Pleasant
    a. Superficial to Meaningful
    a. Ineffective to Effective
    a. Unimportant to Important
1. Potential moderation by the relationship with interaction partner
    a. How close do you feel to [name interaction partner]?
    a. How much do you trust [name interaction partner]?
    a. What is your relationship with [name interaction partner]?
1. Potential moderation by key need characteristics
    a. [name interaction partner] helped fulfill your goal [free-text entry interaction key need].
    a. How important was your goal ([free-text interaction key need]) to you?
1. Potential moderation by the interaction characteristics
    a. How long was the interaction? (in minutes)
    a. What was the main language during the interaction?
    a. The interaction was: With a single other / In a group
    
_Full variable information is available in the codebook ('Codebook_AOT-M_ItemsPerSection.xlsx')_

## Indices
<!-- If any measurements are  going to be combined into an index (or even a mean), what measures will you use and how will they be combined? Include either a formula or a precise description of your method. If your are using a more complicated statistical method to combine measures (e.g. a factor analysis), you can note that here but describe the exact method in the analysis plan section.

If you are using multiple pieces of data to construct a single variable, how will this occur? Both the data that are included and the formula or weights for each measure must be specified. Standard summary statistics, such as "means" do not require a formula, though more complicated indices require either the exact formula or, if it is an established index in the field, the index must be unambiguously defined. For example, "biodiversity index" is too broad, whereas "Shannon’s biodiversity index" is appropriate.

Example: We will take the mean of the two questions above to create a single measure of 'brownie enjoyment.'  -->

1. Mean Allport's conditions. We create a mean-averaged index of Allport's conditions in response to past findings indicating that the conditions are best conceptualized jointly and as functioning together rather than as fully independent factors [@Pettigrew2006, p. 766]. Similar to past studies we thus hope to build a global indicator [e.g., see @Pettigrew2006]. As with other indices we will ensure that the individual items indeed relate to a common latent construct and are  meaningfully combine in an index. If this is not possible we will create sub-indices and/or assess the impact of the conditions separately.
    a. The interaction with [name interaction partner] was on equal footing (same status)
    a. [name interaction partner] shared your goal ([free-text entry interaction key need])
    a. The interaction with [name interaction partner] was cooperative
    a. The interaction with [name interaction partner] was voluntary
1. Mean belongingness during intergroup contact
    a. I shared information about myself. 
    a. [name interaction partner] shared information about themselves.
1. Mean alternative interaction quality definition ("Overall, the interaction with [name interaction partner] was ...")
    a. Unpleasant to Pleasant
    a. Superficial to Meaningful
    a. Ineffective to Effective
    a. Unimportant to Important


# Analysis Plan
<!-- You may describe one or more confirmatory analysis in this preregistration. Please remember that all analyses specified below must be reported in the final article, and any additional analyses must be noted as exploratory or hypothesis generating.

A confirmatory analysis plan must state up front which variables are predictors (independent) and which are the outcomes (dependent), otherwise it is an exploratory analysis. You are allowed to describe any exploratory work here, but a clear confirmatory analysis is required. -->


## Statistical models
<!-- What statistical model will you use to test each hypothesis? Please include the type of model (e.g. ANOVA, multiple regression, SEM, etc) and the specification of the model (this includes each variable that will be included as predictors, outcomes, or covariates). Please specify any interactions, subgroup analyses, pairwise or complex contrasts, or follow-up tests from omnibus tests. If you plan on using any positive controls, negative controls, or manipulation checks you may mention that here. Remember that any test not included here must be noted as an exploratory test in your final article.

This is perhaps the most important and most complicated question within the preregistration. As with all of the other questions, the key is to provide a specific recipe for analyzing the collected data. Ask yourself: is enough detail provided to run the same analysis again with the information provided by the user? Be aware for instances where the statistical models appear specific, but actually leave openings for the precise test. See the following examples:

- If someone specifies a 2x3 ANOVA with both factors within subjects, there is still flexibility with the various types of ANOVAs that could be run. Either a repeated measures ANOVA (RMANOVA) or a multivariate ANOVA (MANOVA) could be used for that design, which are two different tests. 
- If you are going to perform a sequential analysis and check after 50, 100, and 150 samples, you must also specify the p-values you’ll test against at those three points.

Example:  We will use a one-way between subjects ANOVA to analyze our results. The manipulated, categorical independent variable is 'sugar' whereas the dependent variable is our taste index. -->

We will use a sequential analysis strategy in line with our proposed hypotheses. Given the nested structure of much of our data we test many of our hypotheses using a multilevel approach, where $y_{ti}$ denotes the response at measurement occasion $t$ ($t = 1, ...,T_i$; level 1) for individual $i$ ($i = 1, ..., n$; level 2). It should be noted that we will follow a hierarchical modeling approach. We follow the common four-step procedure [e.g., @Bliese2013]: (1) Test whether enough variation exists within and between participants to justify a multilevel structure, (2) (sequentially) add key predictors, (3) check whether a random slope explains an adequate amount of variance, and (4) check for autocorrelations and heteroscedasticity. For brevity we will only present the full multilevel regression formulas below.

1. Contact Hypothesis (using between participant aggregates only to meaningfully include interaction frequency)
    a. Correlation: $r_{InteractionFrequency, OutgroupAttitudes} \neq 0$
    a. T-test: $\mu_{0utgroupInteraction} > \mu_{IngroupInteraction}$ (to build confidence in the persistence of the contact effect, we additionally compare the attitudes after an outgroup interaction to attitudes after no outgroup interaction (i.e., including instances where participants had no interaction at all).)
    a. Regression: $Attitude = AverageContactFreq \times AverageContactQual$
1. Allport's Conditions
    a. Regression: $Attitude_{ti} = \gamma_{00} + \gamma_{10}AllportConditions_{ti} + u_{0i} + u_{1i} + e_{ti}$
    a. Regression: $Attitude_{ti} = \gamma_{00} + \gamma_{10}AllportConditions_{ti} + \gamma_{20}InteractionQuality_{ti} + u_{0i} + u_{1i} + e_{ti}$
    
        with $\begin{bmatrix} u_{0i}\\ u_{1i}\end{bmatrix} \sim \mathcal{N}(0,\Omega_u): \Omega_u=\begin{bmatrix} \tau_{0}^2 & \\ \tau_{01} & \tau_{1}^2 \end{bmatrix}$ and $e_{ti} \sim \mathcal{N}(0,\sigma^2)$
1. Key Need Fulfillment
    a. Regression: $Attitude_{ti} = \gamma_{00} + \gamma_{10}KeyNeedFulfill_{ti} + u_{0i} + u_{1i} + e_{ti}$
    a. Regression: $InteractionQuality_{ti} = \gamma_{00} + \gamma_{10}KeyNeedFulfill_{ti} + u_{0i} + u_{1i} + e_{ti}$
    a. Regression: $Attitude_{ti} = \gamma_{00} + \gamma_{10}KeyNeedFulfill_{ti} + \gamma_{20}InteractionQuality_{ti} + u_{0i} + u_{1i} + e_{ti}$
    a. Regression: $Attitude_{ti} = KeyNeedFulfill_{ti} \times OutgroupInteraction_{ti} + u_{0i} + u_{1i} + e_{ti}$
    a. Regression: $Attitude_{ti} = \gamma_{00} + \gamma_{10}KeyNeedFulfill_{ti} + \gamma_{20}Autonomy_{ti} + \gamma_{30}Competence_{ti} + \gamma_{40}Relatedness_{ti} + u_{0i} + u_{1i} + e_{ti}$
    
        with $\begin{bmatrix} u_{0i}\\ u_{1i}\end{bmatrix} \sim \mathcal{N}(0,\Omega_u): \Omega_u=\begin{bmatrix} \tau_{0}^2 & \\ \tau_{01} & \tau_{1}^2 \end{bmatrix}$ and $e_{ti} \sim \mathcal{N}(0,\sigma^2)$
1. Comparison with Allport's Conditions
    a. Model Comparison: $AIC_{KeyNeedModel} > AIC_{AllportModel}$
    a. Regression: $Attitude_{ti} = \gamma_{00} + \gamma_{10}KeyNeedFulfill_{ti} + \gamma_{20}AllportConditions_{ti} + u_{0i} + u_{1i} + e_{ti}$
    
        with $\begin{bmatrix} u_{0i}\\ u_{1i}\end{bmatrix} \sim \mathcal{N}(0,\Omega_u): \Omega_u=\begin{bmatrix} \tau_{0}^2 & \\ \tau_{01} & \tau_{1}^2 \end{bmatrix}$ and $e_{ti} \sim \mathcal{N}(0,\sigma^2)$
    

## Transformations
<!-- If you plan on transforming, centering, recoding the data, or will require a coding scheme for categorical variables, please describe that process. If any categorical predictors are included in a regression, indicate how those variables will be coded (e.g. dummy coding, summation coding, etc.) and what the reference category will be.

Example: The "Effect of sugar on brownie tastiness" does not require any additional transformations. However, if it were using a regression analysis and each level of sweet had been categorically described (e.g. not sweet, somewhat sweet, sweet, and very sweet), 'sweet' could be dummy coded with 'not sweet' as the reference category. -->

We will mean-center all level-one predictors within participants (i.e., cluster mean centering). This is relevant for any predictor variable during the interaction (e.g., key need fulfillment, interaction quality, ...). We mean-center within-person predictors, to meaningfully distinguish within and between person variances and because we obtain a meaningful intercept when having a random slope model [e.g., @Hamaker2014].


## Inference criteria
<!-- What criteria will you use to make inferences? Please describe the information youÍll use (e.g. p-values, bayes factors, specific model fit indices), as well as cut-off criterion, where appropriate. Will you be using one or two tailed tests for each of your analyses? If you are comparing multiple conditions or testing multiple hypotheses, will you account for this?

p-values, confidence intervals, and effect sizes are standard means for making an inference, and any level is acceptable, though some criteria must be specified in this or previous fields. Bayesian analyses should specify a Bayes factor or a credible interval. If you are selecting models, then how will you determine the relative quality of each? In regards to multiple comparisons, this is a question with few "wrong" answers. In other words, transparency is more important than any specific method of controlling the false discovery rate or false error rate. One may state an intention to report all tests conducted or one may conduct a specific correction procedure; either strategy is acceptable.

Example: We will use the standard p<.05 criteria for determining if the ANOVA and the post hoc test suggest that the results are significantly different from those expected if the null hypothesis were correct. The post-hoc Tukey-Kramer test adjusts for multiple comparisons. -->

We will use the standard p<.05 criteria for determining whether the correlation and regression coefficients are statistically significant. However, given the large sample size we will place a particular emphasis on effect sizes in our interpretations of the results.

## Data exclusion
<!-- How will you determine what data or samples, if any, to exclude from your analyses? How will outliers be handled? Will you use any awareness check? Any rule for excluding a particular set of data is acceptable. One may describe rules for excluding a participant or for identifying outlier data.

Example: No checks will be performed to determine eligibility for inclusion besides verification that each subject answered each of the three tastiness indices. Outliers will be included in the analysis. -->

No checks will be performed to determine eligibility for inclusion besides verification that each subject answered each of the variables of interest for a given analysis. Outliers will generally be included in analyses, however we will use sensitivity analyses to assess the robustness of the results to outliers.


## Missing data
<!-- How will you deal with incomplete or missing data? Any relevant explanation is acceptable. As a final reminder, remember that the final analysis must follow the specified plan, and deviations must be either strongly justified or included as a separate, exploratory analysis.

Example: If a subject does not complete any of the three indices of tastiness, that subject will not be included in the analysis. -->

Given the (expectedly) large sample size of contemporaneous measurements, we will remove all instances during which a participant did not respond to any of the relevant variables.


## Exploratory analyses (optional)
<!-- If you plan to explore your data set to look for unexpected differences or relationships, you may describe those tests here. An exploratory test is any test where a prediction is not made up front, or there are multiple possible tests that you are going to use. A statistically significant finding in an exploratory test is a great way to form a new confirmatory hypothesis, which could be registered at a later time.

Example: We expect that certain demographic traits may be related to taste preferences. Therefore, we will look for relationships between demographic variables (age, gender, income, and marital status) and the primary outcome measures of taste preferences. -->


@Brown2005 proposed in their integrative theory of intergroup contact that "group salience" should moderate the positive effect of intergroup contact on outgroup attitudes. They argue that especially when the outgroup membership is salient, the positive attitudes should generalize from the outgroup individual to the general outgroup. We have data to test this hypothesis within a large intensive longitudinal dataset of daily intergroup interactions. We do this by seperately assessing attitudes towards the outgroup interaction partner and the outgroup generally. And by assessing whether perceiving the interaction as representative of the outgroup moderates the positive contact effects.

To build confidence in our conclusions about the role of contact quality we calculate an alternative measure of interaction quality that includes perceived pleasantness, meaning, effectiveness, and importance of the interaction.

We expect that certain contextual characteristics may be related to the positive effects of high quality outgroup interactions. Therefore, we will look for the effect of key need fulfillment on outgroup attitudes while also including information about the interaction partner (perceived closeness, trust, relationship), the interaction characteristics (duration, interaction language, group vs. dyadic), as well as characteristics of the key need (importance of the need, fulfillment due to the interaction partner).


# Other

## Other (Optional)
<!-- If there is any additional information that you feel needs to be included in your preregistration, please enter it here. Literature cited, disclosures of any related work such as replications or work that uses the same data, or other context that will be helpful for future readers would be appropriate here. -->

Not applicable.


# References
## 
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
\noindent
